---
- name: Ensure PIP config directory exist and can be written in.
  file:
    dest: "{{ pipconfig_dir }}"
    mode: "{{ (pipconfig_dir_mode | default(None,true) == None) | ternary(omit, pipconfig_dir_mode) }}"
    state: directory

- name: Install PIP config
  template:
    dest: "{{ pipconfig_dir + '/' + pipconfig_file }}"
    mode: "{{ pipconfig_file_mode }}"
    src: "pip.conf"

# vim: et:sw=2:syntax=yaml:ts=2:
